### ISSUE TITLE
use dataurlencode

### ISSUE THREAD

**Issue by libin0811** [libetl/curl#249]
**Describe the bug**
has error when i use dataurlencode method 

**Environment**
Special configuration in /etc/hosts ?
Reverse proxy ?
VPN ? Y/N
Proxy ? Y/N

**Curl command line**
Please provide (if allowed) the full curl command line
And (if possible) give me the access to hit the endpoint myself.
![image](https://user-images.githubusercontent.com/44914845/187822409-c65457f8-82ca-4ab3-8a6d-b9e91a5f8737.png)

**Expected behavior**
A clear and concise description of what you expected to happen while using the real cURL command.

**Stacktrace**
2022-09-01 Caused by: org.toilelibre.libe.curl.Curl$CurlException: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --dataurlencode
2022-09-01 	at org.toilelibre.libe.curl.ReadArguments.getCommandLineFromRequest(ReadArguments.java:34) ~[curl-0.0.39.jar:?]
2022-09-01 	at org.toilelibre.libe.curl.ReadArguments.getCommandLineFromRequest(ReadArguments.java:18) ~[curl-0.0.39.jar:?]
2022-09-01 	at org.toilelibre.libe.curl.Curl.curl(Curl.java:67) ~[curl-0.0.39.jar:?]
2022-09-01 	at org.toilelibre.libe.curl.Curl$CurlArgumentsBuilder.run(Curl.java:171) ~[curl-0.0.39.jar:?]
2022-09-01 	at com.baosight.eplat.be.ce.service.ServiceBECE460.insertMachineByGrovvyScript(ServiceBECE460.java:442) ~[classes/:2.0.0-SNAPSHOT]
2022-09-01 	... 152 more
2022-09-01 Caused by: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --dataurlencode
2022-09-01 	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:407) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:384) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60) ~[commons-cli-1.4.jar:1.4]
2022-09-01 	at org.toilelibre.libe.curl.ReadArguments.getCommandLineFromRequest(ReadArguments.java:31) ~[curl-0.0.39.jar:?]
2022-09-01 	at org.toilelibre.libe.curl.ReadArguments.getCommandLineFromRequest(ReadArguments.java:18) ~[curl-0.0.39.jar:?]
2022-09-01 	at org.toilelibre.libe.curl.Curl.curl(Curl.java:67) ~[curl-0.0.39.jar:?]
2022-09-01 	at org.toilelibre.libe.curl.Curl$CurlArgumentsBuilder.run(Curl.java:171) ~[curl-0.0.39.jar:?]

**Comment by libin0811** [comment]
"--data-urlencode"   or  "--dataurlencode" ?

**Comment by libetl** [comment]
interesting...

**Comment by libetl** [comment]
it is a bug with the ArgumentsBuilderGenerator
the generator adds the short opt method and only the long opt method if the method names are different.
It should be the other way around
the generator should add the long opt method and only the short opt method if the method names are different.

**Comment by libetl** [comment]
please retest with 0.0.40
